### Create employee
POST http://localhost:3000/employees.json
Content-Type: application/json 

{
  "first_name": "Bruce",
  "last_name": "Wayne",
  "email": "batman@example.com",
  "phone": "345-876-0987",
  "job_title": "Dark Knight",
  "department_id": "1"
}