@jwt = eyJhbGciOiJIUzI1NiJ9.eyJlbXBsb3llZV9pZCI6MTcsImV4cCI6MTY1NzkxODMxNn0.5SjNSks02Je8uSIDJ4Yjm3z643NFsRkgBr-sWU1u0IA

### Create employee
POST http://localhost:3000/employees.json
Authorization: Bearer {{jwt}}
Content-Type: application/json 

{
  "first_name": "Bruce",
  "last_name": "Wayne Jr.",
  "email": "batmanjr@example.com",
  "phone": "345-876-0987",
  "job_title": "Dark Knight",
  "department_id": "1",
  "password": "password", 
  "password_confirmation": "password", 
  "admin": true
}

### Update employee
PATCH  http://localhost:3000/employees/8.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
   "job_title": "Wonder Woman"
}

### Destroy employee
DELETE http://localhost:3000/employees/15.json


### Create department
POST http://localhost:3000/departments.json
Content-Type: application/json 

{
  "name": "Internal Affairs",
  "manager": "Snitch",
  "code": "1"
}

### Update department
PATCH  http://localhost:3000/departments/4.json
Content-Type: application/json

{
   "code": "789"
}

### Destroy department
DELETE http://localhost:3000/departments/2.json

### sessions create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "id": 17,
  "password": "password"
}
