### Create employee
POST http://localhost:3000/employees.json
Content-Type: application/json 

{
  "first_name": "",
  "last_name": "Wayne",
  "email": "batman@example.com",
  "phone": "345-876-0987",
  "job_title": "Dark Knight",
  "department_id": "1"
}

### Update employee
PATCH  http://localhost:3000/employees/16.json
Content-Type: application/json

{
  "job_title": "Assistant Orphan"
}

### Destroy employee
DELETE http://localhost:3000/employees/15.json